### ISSUE TITLE
SQLException when trying to get a document?

### ISSUE THREAD

**Issue by ecnivo** [ecnivo/Flow#45]
Double click on a document 
Login 'z' pass 'z' and try "tesfile"
![image](https://cloud.githubusercontent.com/assets/10538710/12366200/b1ba1f3e-bba7-11e5-9fdc-4ec13535e2d8.png)

**Comment by ecnivo** [comment]
Sorry, gotta reopen it
![image](https://cloud.githubusercontent.com/assets/10538710/12369101/a21e14e0-bbc0-11e5-9358-6b5f8dac6343.png)

**Comment by Bimde** [comment]
Missing 'TEXT' tag on column creation... Fixed in https://github.com/ecnivo/Flow/commit/07c88083073ab97a6ff20303e1abb6e77caf5a6e

**Comment by ecnivo** [comment]
Are you sure?

**Comment by ecnivo** [comment]
Still broken! 
![image](https://cloud.githubusercontent.com/assets/10538710/12369348/a1f8cade-bbc3-11e5-8177-0330b5c9032f.png)

**Comment by Bimde** [comment]
That is unrelated to the original issue. This is an issue with wiping the version table.
